version: "3.8"
services:
  dev_postgres_db:
    # See https://hub.docker.com/_/postgres for details about configuration
    image: "postgres:14.3-alpine"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./.postgresdata:/var/lib/postgresql/data
    user: root
    # Should match with the appsettings.Development.json file/s
    environment:
      - POSTGRES_USER=db_dev_superuser
      - POSTGRES_PASSWORD=db_dev_password
      - POSTGRES_DB=radixdlt_ledger
  dev_pgadmin:
    # See https://www.pgadmin.org/docs/pgadmin4/development/container_deployment.html
    image: "dpage/pgadmin4:6.12"
    ports:
      - "127.0.0.1:5050:80"
    volumes:
      - ./.pgadmin-dev/servers.json:/pgadmin4/servers.json
      - ./.pgadmin-dev/.pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@example.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_CONFIG_SERVER_MODE=False # Don't show login screen
      # Override some other things due to turning Server Mode off - https://www.pgadmin.org/docs/pgadmin4/development/config_py.html
      - PGADMIN_CONFIG_DATA_DIR='/var/lib/pgadmin'
      - PGADMIN_CONFIG_LOG_FILE='/var/lib/pgadmin/pgadmin4.log'
      - PGADMIN_CONFIG_SESSION_EXPIRATION_TIME=7
      - PGADMIN_CONFIG_USER_INACTIVITY_TIMEOUT=0
      - PGADMIN_CONFIG_ENABLE_PSQL=True
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False # PGAdmin should only be used to connect to the db in dev
