version: "3.8"
services:
  postgres_db:
    # See https://hub.docker.com/_/postgres for details about configuration
    image: "postgres:14-alpine"
    ports:
      - "5532:5432" # This allows you to connect to the database locally on port localhost:5532
    volumes:
      - ./.postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_SUPERUSER}"
      POSTGRES_PASSWORD: "${POSTGRES_SUPERUSER_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB_NAME}"
  data_aggregator:
    depends_on:
      - postgres_db
    build:
      context: "../"
      dockerfile: "./src/DataAggregator/Dockerfile"
    ports:
      - "5207:80" # This allows you to connect to the API (for root and health checks) at http://localhost:5207
      - "1234:1234" # This allows you to connect to the metrics API at http://localhost:1234
    environment:
      # WIPE_DATABASE: "true"
      ASPNETCORE_URLS: "http://*:80" # Binds to 80 on all interfaces
      RADIX_NG_AGGREGATOR__PrometheusMetricsPort: "1234"
      RADIX_NG_AGGREGATOR__MaxWaitForDbOnStartupMs: "${MAX_DB_WAIT_MS_ON_START}" # Wait for PostGres to boot up
      RADIX_NG_AGGREGATOR__DisableCoreApiHttpsCertificateChecks: "${DISABLE_CORE_API_CERTIFICATE_CHECKS}"
      RADIX_NG_AGGREGATOR__NetworkName: "${NETWORK_NAME}"
      RADIX_NG_AGGREGATOR__ConnectionStrings__AggregatorDbContext: "Host=postgres_db:5432;Database=${POSTGRES_DB_NAME};Username=${POSTGRES_SUPERUSER};Password=${POSTGRES_SUPERUSER_PASSWORD}"
      RADIX_NG_AGGREGATOR__CoreApiNodes__0__Name: "${NODE_0_NAME}"
      RADIX_NG_AGGREGATOR__CoreApiNodes__0__CoreApiAddress: "${NODE_0_CORE_API_ADDRESS}"
      RADIX_NG_AGGREGATOR__CoreApiNodes__0__CoreApiAuthorizationHeader: "${NODE_0_CORE_API_AUTHORIZATION_HEADER}"
      RADIX_NG_AGGREGATOR__CoreApiNodes__0__TrustWeighting: "1"
      RADIX_NG_AGGREGATOR__CoreApiNodes__0__Enabled: "${NODE_0_ENABLED}"
      RADIX_NG_AGGREGATOR__CoreApiNodes__1__Name: "${NODE_1_NAME}"
      RADIX_NG_AGGREGATOR__CoreApiNodes__1__CoreApiAddress: "${NODE_1_CORE_API_ADDRESS}"
      RADIX_NG_AGGREGATOR__CoreApiNodes__1__CoreApiAuthorizationHeader: "${NODE_1_CORE_API_AUTHORIZATION_HEADER}"
      RADIX_NG_AGGREGATOR__CoreApiNodes__1__TrustWeighting: "1"
      RADIX_NG_AGGREGATOR__CoreApiNodes__1__Enabled: "${NODE_1_ENABLED}"
      RADIX_NG_AGGREGATOR__CoreApiNodes__2__Name: "${NODE_2_NAME}"
      RADIX_NG_AGGREGATOR__CoreApiNodes__2__CoreApiAddress: "${NODE_2_CORE_API_ADDRESS}"
      RADIX_NG_AGGREGATOR__CoreApiNodes__2__CoreApiAuthorizationHeader: "${NODE_2_CORE_API_AUTHORIZATION_HEADER}"
      RADIX_NG_AGGREGATOR__CoreApiNodes__2__TrustWeighting: "1"
      RADIX_NG_AGGREGATOR__CoreApiNodes__2__Enabled: "${NODE_2_ENABLED}"
      RADIX_NG_AGGREGATOR__CoreApiNodes__3__Name: "${NODE_3_NAME}"
      RADIX_NG_AGGREGATOR__CoreApiNodes__3__CoreApiAddress: "${NODE_3_CORE_API_ADDRESS}"
      RADIX_NG_AGGREGATOR__CoreApiNodes__3__CoreApiAuthorizationHeader: "${NODE_3_CORE_API_AUTHORIZATION_HEADER}"
      RADIX_NG_AGGREGATOR__CoreApiNodes__3__TrustWeighting: "1"
      RADIX_NG_AGGREGATOR__CoreApiNodes__3__Enabled: "${NODE_3_ENABLED}"
      RADIX_NG_AGGREGATOR__CoreApiNodes__4__Name: "${NODE_4_NAME}"
      RADIX_NG_AGGREGATOR__CoreApiNodes__4__CoreApiAddress: "${NODE_4_CORE_API_ADDRESS}"
      RADIX_NG_AGGREGATOR__CoreApiNodes__4__CoreApiAuthorizationHeader: "${NODE_4_CORE_API_AUTHORIZATION_HEADER}"
      RADIX_NG_AGGREGATOR__CoreApiNodes__4__TrustWeighting: "1"
      RADIX_NG_AGGREGATOR__CoreApiNodes__4__Enabled: "${NODE_4_ENABLED}"
  gateway_api:
    depends_on:
      - postgres_db
      - data_aggregator
    build:
      context: "../"
      dockerfile: "./src/GatewayAPI/Dockerfile"
    ports:
      - "5308:80" # This allows you to connect to the API at http://localhost:5308
      - "1235:1235" # This allows you to connect to the metrics API at http://localhost:1235
    environment:
      ASPNETCORE_URLS: "http://*:80" # Binds to 80 on all interfaces
      RADIX_NG_API__PrometheusMetricsPort: "1235"
      RADIX_NG_API__MaxWaitForDbOnStartupMs: "${MAX_DB_WAIT_MS_ON_START}" # Wait for PostGres to boot up
      RADIX_NG_API__DisableCoreApiHttpsCertificateChecks: "${DISABLE_CORE_API_CERTIFICATE_CHECKS}"
      RADIX_NG_API__NetworkName: "${NETWORK_NAME}"
      RADIX_NG_API__EnableSwagger: "${ENABLE_SWAGGER}"
      RADIX_NG_API__ConnectionStrings__ReadOnlyDbContext: "Host=postgres_db:5432;Database=${POSTGRES_DB_NAME};Username=${POSTGRES_SUPERUSER};Password=${POSTGRES_SUPERUSER_PASSWORD}"
      RADIX_NG_API__ConnectionStrings__ReadWriteDbContext: "Host=postgres_db:5432;Database=${POSTGRES_DB_NAME};Username=${POSTGRES_SUPERUSER};Password=${POSTGRES_SUPERUSER_PASSWORD}"
      RADIX_NG_API__CoreApiNodes__0__Name: "${NODE_0_NAME}"
      RADIX_NG_API__CoreApiNodes__0__CoreApiAddress: "${NODE_0_CORE_API_ADDRESS}"
      RADIX_NG_API__CoreApiNodes__0__CoreApiAuthorizationHeader: "${NODE_0_CORE_API_AUTHORIZATION_HEADER}"
      RADIX_NG_API__CoreApiNodes__0__RequestWeighting: "1"
      RADIX_NG_API__CoreApiNodes__0__Enabled: "${NODE_0_ENABLED}"
      RADIX_NG_API__CoreApiNodes__1__Name: "${NODE_1_NAME}"
      RADIX_NG_API__CoreApiNodes__1__CoreApiAddress: "${NODE_1_CORE_API_ADDRESS}"
      RADIX_NG_API__CoreApiNodes__1__CoreApiAuthorizationHeader: "${NODE_1_CORE_API_AUTHORIZATION_HEADER}"
      RADIX_NG_API__CoreApiNodes__1__RequestWeighting: "1"
      RADIX_NG_API__CoreApiNodes__1__Enabled: "${NODE_1_ENABLED}"
      RADIX_NG_API__CoreApiNodes__2__Name: "${NODE_2_NAME}"
      RADIX_NG_API__CoreApiNodes__2__CoreApiAddress: "${NODE_2_CORE_API_ADDRESS}"
      RADIX_NG_API__CoreApiNodes__2__CoreApiAuthorizationHeader: "${NODE_2_CORE_API_AUTHORIZATION_HEADER}"
      RADIX_NG_API__CoreApiNodes__2__RequestWeighting: "1"
      RADIX_NG_API__CoreApiNodes__2__Enabled: "${NODE_2_ENABLED}"
      RADIX_NG_API__CoreApiNodes__3__Name: "${NODE_3_NAME}"
      RADIX_NG_API__CoreApiNodes__3__CoreApiAddress: "${NODE_3_CORE_API_ADDRESS}"
      RADIX_NG_API__CoreApiNodes__3__CoreApiAuthorizationHeader: "${NODE_3_CORE_API_AUTHORIZATION_HEADER}"
      RADIX_NG_API__CoreApiNodes__3__RequestWeighting: "1"
      RADIX_NG_API__CoreApiNodes__3__Enabled: "${NODE_3_ENABLED}"
      RADIX_NG_API__CoreApiNodes__4__Name: "${NODE_4_NAME}"
      RADIX_NG_API__CoreApiNodes__4__CoreApiAddress: "${NODE_4_CORE_API_ADDRESS}"
      RADIX_NG_API__CoreApiNodes__4__CoreApiAuthorizationHeader: "${NODE_4_CORE_API_AUTHORIZATION_HEADER}"
      RADIX_NG_API__CoreApiNodes__4__RequestWeighting: "1"
      RADIX_NG_API__CoreApiNodes__4__Enabled: "${NODE_4_ENABLED}"
