name: release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-22.04
    environment: release
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2
        with:
          dotnet-version: 7.0.x
      - name: Build linux binaries
        run: |
          cd apps/DataAggregator
          dotnet publish --runtime linux-x64 --configuration Release --self-contained false -p:PublishReadyToRun=true -p:DebugType=None -p:DebugSymbols=false --output ./output
          cd ../DatabaseMigrations
          dotnet publish --runtime linux-x64 --configuration Release --self-contained false -p:PublishReadyToRun=true -p:DebugType=None -p:DebugSymbols=false --output ./output
          cd ../GatewayApi
          dotnet publish --runtime linux-x64 --configuration Release --self-contained false -p:PublishReadyToRun=true -p:DebugType=None -p:DebugSymbols=false --output ./output
          cd ../..
          zip -r data-aggregator.zip apps/DataAggregator/output/
          zip -r database-migrations.zip apps/DatabaseMigrations/output/
          zip -r gateway-api.zip apps/GatewayApi/output/

      - name: Upload DataAggreagtor zip
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./data-aggregator.zip
          asset_name: data-aggregator-${{ github.event.release.tag_name }}-linux-x64.zip
          asset_content_type: application/zip
      - name: Upload GatewayAPI zip
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./gateway-api.zip
          asset_name: gateway-api-${{ github.event.release.tag_name }}-linux-x64.zip
          asset_content_type: application/zip
      - name: Upload DatabseMigrations zip
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./database-migrations.zip
          asset_name: database-migrations-${{ github.event.release.tag_name }}-linux-x64.zip
          asset_content_type: application/zip

  setup-tags:
    runs-on: ubuntu-22.04
    outputs:
      version-suffix: ${{ steps.setup_tags.outputs.version-suffix }}
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - name: Get rele ase
        id: get_release
        uses: bruceadams/get-release@f589ce0779c7bef1faf175f7488c972eb47dc046
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Setup tags for docker image
        id: setup_tags
        uses: ./.github/actions/set-variables
        with:
          github_event_name: ${{ github.event_name }}
          github_action_name: ${{ github.event.action}}
      - name: Publish Gateway Settings
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          path: Directory.Build.props
          name: build_props
          retention-days: 1

  docker-database-migrations-dockerhub:
    name: AMD DatabaseMigrations
    needs:
      - setup-tags
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/docker-build.yml@main
    with:
      runs_on: ubuntu-22.04
      image_registry: "docker.io"
      image_organization: "radixdlt"
      image_name: "babylon-ng-database-migrations"
      tag: ${{ needs.setup-tags.outputs.version-suffix }}-amd64
      context: "."
      dockerfile: "./apps/DatabaseMigrations/Dockerfile"
      platforms: "linux/amd64"
      environment: release
      cache_tag_suffix: "release"
      enable_dockerhub: "true"
      restore_artifact: "true"
      artifact_location: "./"
      artifact_name: build_props
      provenance: "false"
    secrets:
      role_to_assume: ${{ secrets.DOCKERHUB_RELEASER_ROLE }}

  docker-database-migrations-dockerhub-arm:
    name: ARM DatabaseMigrations
    needs:
      - setup-tags
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/docker-build.yml@main
    with:
      runs_on: babylon-gateway-arm
      image_registry: "docker.io"
      image_organization: "radixdlt"
      image_name: "babylon-ng-database-migrations"
      tag: ${{ needs.setup-tags.outputs.version-suffix }}-arm64
      context: "."
      dockerfile: "./apps/DatabaseMigrations/Dockerfile"
      platforms: "linux/arm64"
      environment: release
      cache_tag_suffix: "release"
      enable_dockerhub: "true"
      restore_artifact: "true"
      artifact_location: "./"
      artifact_name: build_props
      provenance: "false"
    secrets:
      role_to_assume: ${{ secrets.DOCKERHUB_RELEASER_ROLE }}
  
  docker-data-aggregator-dockerhub:
    name: AMD DataAggregator
    needs:
      - setup-tags
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/docker-build.yml@main
    with:
      runs_on: ubuntu-22.04
      image_registry: "docker.io"
      image_organization: "radixdlt"
      image_name: "babylon-ng-data-aggregator"
      tag: ${{ needs.setup-tags.outputs.version-suffix }}-amd64
      context: "."
      dockerfile: "./apps/DataAggregator/Dockerfile"
      platforms: "linux/amd64"
      environment: release
      cache_tag_suffix: "release"
      enable_dockerhub: "true"
      restore_artifact: "true"
      artifact_location: "./"
      artifact_name: build_props
      provenance: false
    secrets:
      role_to_assume: ${{ secrets.DOCKERHUB_RELEASER_ROLE }}

  docker-data-aggregator-dockerhub-arm:
    name: ARM DataAggregator
    needs:
      - setup-tags
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/docker-build.yml@main
    with:
      runs_on: babylon-gateway-arm
      image_registry: "docker.io"
      image_organization: "radixdlt"
      image_name: "babylon-ng-data-aggregator"
      tag: ${{ needs.setup-tags.outputs.version-suffix }}-arm64
      context: "."
      dockerfile: "./apps/DataAggregator/Dockerfile"
      platforms: "linux/arm64"
      environment: release
      cache_tag_suffix: "release"
      enable_dockerhub: "true"
      restore_artifact: "true"
      artifact_location: "./"
      artifact_name: build_props
      provenance: false
    secrets:
      role_to_assume: ${{ secrets.DOCKERHUB_RELEASER_ROLE }}
  
  docker-gateway-api-dockerhub:
    name: AMD GatewayApi
    needs:
      - setup-tags
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/docker-build.yml@main
    with:
      runs_on: ubuntu-22.04
      image_registry: "docker.io"
      image_organization: "radixdlt"
      image_name: "babylon-ng-gateway-api"
      tag: ${{ needs.setup-tags.outputs.version-suffix }}-amd64
      context: "."
      dockerfile: "./apps/GatewayApi/Dockerfile"
      platforms: "linux/amd64"
      environment: release
      cache_tag_suffix: "release"
      enable_dockerhub: "true"
      restore_artifact: "true"
      artifact_location: "./"
      artifact_name: build_props
      provenance: false
    secrets:
      role_to_assume: ${{ secrets.DOCKERHUB_RELEASER_ROLE }}

  docker-gateway-api-dockerhub-arm:
    name: ARM GatewayApi
    needs:
      - setup-tags
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/docker-build.yml@main
    with:
      runs_on: babylon-gateway-arm
      image_registry: "docker.io"
      image_organization: "radixdlt"
      image_name: "babylon-ng-gateway-api"
      tag: ${{ needs.setup-tags.outputs.version-suffix }}-arm64
      context: "."
      dockerfile: "./apps/GatewayApi/Dockerfile"
      platforms: "linux/arm64"
      environment: release
      cache_tag_suffix: "release"
      enable_dockerhub: "true"
      restore_artifact: "true"
      artifact_location: "./"
      artifact_name: build_props
      provenance: false
    secrets:
      role_to_assume: ${{ secrets.DOCKERHUB_RELEASER_ROLE }}

  join-gateway-images:
    name: Gateway
    needs:
      - setup-tags
      - docker-gateway-api-dockerhub
      - docker-gateway-api-dockerhub-arm
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/merge-docker-images.yml@merge-image-workflow
    with: 
      image_name: private-babylon-ng-gateway-api
      image_tag: ${{ needs.setup-tags.outputs.version-suffix }}
      tag_suffix_1: amd64
      tag_suffix_2: arm64
      aws_dockerhub_secret: github-actions/rdxworks/dockerhub-images/release-credentials
    secrets:
      role-to-assume: ${{ secrets.DOCKERHUB_RELEASER_ROLE }}

  join-aggregator-images:
    name: Aggregator
    needs:
      - setup-tags
      - docker-data-aggregator-dockerhub
      - docker-data-aggregator-dockerhub-arm
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/merge-docker-images.yml@merge-image-workflow
    with: 
      image_name: private-babylon-ng-data-aggregator
      image_tag: ${{ needs.setup-tags.outputs.version-suffix }}
      tag_suffix_1: amd64
      tag_suffix_2: arm64
      aws_dockerhub_secret: github-actions/rdxworks/dockerhub-images/release-credentials
    secrets:
      role-to-assume: ${{ secrets.DOCKERHUB_RELEASER_ROLE }}
  
  join-migrations-images:
    name: Migration
    needs:
      - setup-tags
      - docker-database-migrations-dockerhub
      - docker-database-migrations-dockerhub-arm
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/merge-docker-images.yml@merge-image-workflow
    with: 
      image_name: private-babylon-ng-database-migrations
      image_tag: ${{ needs.setup-tags.outputs.version-suffix }}
      tag_suffix_1: amd64
      tag_suffix_2: arm64
      aws_dockerhub_secret: github-actions/rdxworks/dockerhub-images/release-credentials
    secrets:
      role-to-assume: ${{ secrets.DOCKERHUB_RELEASER_ROLE }}